spring:
  application:
    name: rates-app
  mvc:
    path-match:
      matching-strategy: ant-path-matcher
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  datasource:
    url: jdbc:h2:mem:myh2db
    driverClassName: org.h2.Driver
    username: test
    password:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Server config
server:
  port: 9150

# Open API config
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
